### ISSUE TITLE
Be Able to add wild cards

### ISSUE THREAD

**Issue by RankXerox69** [markhallen/Remove-ApplicationByDisplayName#1]
HI, Please could you make the DisplayName string evaluation as Like and not exact match ??? 
it would be nice be able to find different versions etc..

**Comment by markhallen** [comment]
Resolved by commit: [Allow wildcards in the DisplayName through use of -like](https://github.com/markhallen/Remove-ApplicationByDisplayName/commit/d1c78691985ae8db96f0dd248f79b1f1c8dd3781)
